name: mime_dart
description: Get Mime Types, Extensions, Compressible for Dart and Flutter. Inspired from IANA Databse
version: 3.0.0
homepage: https://github.com/niteshsh4rma/mime_dart

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  lints: ^2.0.0
  test: ^1.16.0

dependencies: 
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
